language: node_js
node_js:
- '8'
sudo: false
script: npm test
branches:
  only:
  - master
env:
  global:
  - secure: As9oYQOFyilaTc+Iye6Wd0HV32u6enCin2hKDGgbn+O9QOfDDHvZ90toeEqhl1QoFlTigXYiT9H7CB1rCdLMk4L3Wcb6wCo/RuesLEsYul4gc8OOda6OK5FNhawdclW63QoO2A/EYTerbmOvJtCSGUmo6nN5JftgeEGIHJvcMGEDBTBqvPMFmvh7vQZHnq2BJ3ZUBPu88UlsY0NJ4i8/to7l56UDFLjwOHsCLvZMF5hEBsYi7BzeUgFbvVRUGIUVv1R8U8i/53WjaVo2u2hSn8L58yDc7WZEq5fk8h1WHte7KkuryI4B6xRFDC6+p5hy0JQ9ExyvSI9o9DYwnfErAS06WE+fmu+img0KLN8dmCobAVmJAFpoxx5lLWKbS9vGAgG4Qwp7C7zLBswK5QdIicL6MOgK0XmCYTHbuNSneGdbPmexOObmgNX3/Er10ZEHcqd//yHK5xFQbsZYIWPexMIIYVeFvRhoCLEqhNoVu2Dxk3K9EfQseTTaMwuA4K9QuIE9F9pc+8plSYqZ7sj1aV/UKfK0sDDAb7Fyvg6H9Ux/LDVjZV9v1pClDhNVwLdNcjH0S2vvxq0DwbbPlfbUZxZ4f+nFw3EPGC4KYqAuQbD0+wiEqdJUdl2mKCbhsQjfzfGGZ9IB6ud7PVyoS3LQIYBdS8k9IaVaHgmHjE+GB40=
  - secure: oeT+C6JBZZzZo00gJhjRnUftspDe7U9O2KwbcKzoRfq8m9f0XaK+LyHAYIEI8D4QnF6zOaMwAU2JYYgCrNFVvyhGMa4ER1l3MhdcMNU4LUPkcVMbsuMrR8J8/AW2iv2j6bfl/U2CYuUZSATvWSwK5nKJDxUtVkgzhhyHfQDOKZu4Ywg0UR14ioiSDY+AjyWNMAZqYNiGuuYph8I5RmcEeOCP/9EMqo2J1j97Oq2bpvvS00eWr+nK6rmIOHb++eWigyh4cPzGH+lunS5ET9VTIM4H0r2TyK94h4zn+7Ma9m/LfAg8FGdo3UzOlsYcVEdNke8Z351zwQNyYG+sKqId/bSUESCafDLrjHwGEGYQYkAis+mmlnUb1XMCs1BN+4+acgfkIPI2NzzSSP2RIapkCLgCPfn6/HUFVYsLfAkOPHErN9IDP19ESEZLVt+l+pmPF6fTSm70hykN9TngeVBCV3P6p1wWjDB8Dfih4UZsI7q6GLMPVtLxU4qKnA9LI0sZG4a/jwqvS2ncrIyI5T3NleXxE3PmL/NagXCnDp6lgOgCR59hM2tiBUuiZMnTgx/khrGB1jWLySD5YFTzuGRUpaV+Wp86f8vq3UzBxe3DJ0mUhkLCKRoEfOX8SpgFRxBSN0ifr6osNoJEPzPAZpcKQoQ042VRBgXniXXxPgOfYLg=
